### ISSUE TITLE
DSB-131 - Charts section data

### ISSUE THREAD

**Issue by miguelpeixe** [lianetoolkit/liane-toolkit#131]
Methods with redis caching (ttl to be defined) to retrieve the following historical data:

- Incoming new Facebook people in the directory
- Facebook interactions from time (containing disaggregated comments and reaction types)
- Top commenters
- Top _reactioners_

The period should start by the date of the campaign creation

**Comment by nefertiter** [comment]
PR available in https://github.com/lianetoolkit/liane-toolkit/pull/165
