### ISSUE TITLE
LIA-139 Bugs from test merge function

### ISSUE THREAD

**Issue by eldardo** [lianetoolkit/liane-toolkit#139]
**DATABASE IMPORT**:

- I created a database with 10 people to upload to Liane.
- The system is expected to load the base and recognize at least 5 repeated potential people to solve.
- The system should add two new people who are not in the database, and increase the number of people in the directory.
- When the import finishes  loading, the unsolved repeated people fields do not appear.
- A person who had the same name in the database as Facebook, automatically merges. The system does not give notice of that merge.

**Manual loading**
If I load a manual person who is already in the database, the system duplicates it and does not resolve the repetition.

This is te xlsx file used for the tests:
[teste_merge.xlsx](https://github.com/lianetoolkit/liane-toolkit/files/4974020/teste_merge.xlsx)

**Comment by nefertiter** [comment]
@eldardo I've updated my brancch CRM-02  with `master` and now no issues like this be taking place. Please review one more time on test server, I'll close this for now, but please open again for any further issues.
