### ISSUE TITLE
Atividade recente: Incluir private reply

### ISSUE THREAD

**Issue by miguelpeixe** [lianetoolkit/liane-toolkit#29]

**Comment by miguelpeixe** [comment]
Há atualmente um bug na API do Facebook em que o parâmetro "can_reply_privately" do comentário, utilizado para verificação se o sistema pode enviar uma mensagem, está sempre retornando **false**.

https://developers.facebook.com/support/bugs/258788208262321/?disable_redirect=0

**Comment by miguelpeixe** [comment]
Este é o issue que está recebendo updates: https://developers.facebook.com/support/bugs/429985290818592/?disable_redirect=0

**Comment by miguelpeixe** [comment]
A última atualização - não oficialmente documentada, mas funciona - é que o token do usuário que gerencia a página deve conter a permissão "business_management".

Ao incluir esse escopo na autenticação - já  aprovada no aplicativo oficial - os comentários voltaram a retornar valores corretos para gestão de comentários aptos à responder de maneira privada.

**Comment by pmarkun** [comment]
Fiz um comentário com meu usuário num post e não estou conseguindo ativar o private reply. Ele aparece no Directory mas dá erro como se eu já tivesse respondido.

Além disso seria importante ter o atalho do private reply no Recent Activities.

**Comment by miguelpeixe** [comment]
@pmarkun a viabilidade de responder um comentário é totalmente condicionada com a API do Facebook, ou seja, verificamos o "can_reply_privately" retornado via API. Podem existir diferentes critérios do Facebook que inviabilizam a possibilidade de responder, não saberia neste momento nomear o que pode ser.

Vou incluir o botão de privately reply no Recent Activities.
