### ISSUE TITLE
Atividade recente - Exibir info das interações do usuário

### ISSUE THREAD

**Issue by miguelpeixe** [lianetoolkit/liane-toolkit#31]

**Comment by pmarkun** [comment]
A interface ficou um pouco confusa. 

Fiquei pensando que podia ter tipo um "profile" mesmo.

![Screenshot_2018-06-20_19-32-28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b22c4b8f532a200117aff2d/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416713e7b549c7a29c8b07af2102343434d0eee1e020a17b8eb8339a3e43e708a5e58e8d7685e74c73c11acba851dbe04e826835d99a4fedb1294b7607caddecd5d340c041183fe5837a99c48cc59fe42e94856b65e.png)

**Comment by miguelpeixe** [comment]
Estranha essa interface, no meu está assim:

![Captura de tela de 2018-06-21 10-59-50.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ceae1f82b317f7d9acf500/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2733dd5b565ed133b505f424ba55c5d5f56e0ebc969f9ec6923ce4e01ffd43f5d74c63f42a9be871ebf00bb208b4d82b4bd8f1ec6e02f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee34450ac1a3063e577367955d9.png)

**Comment by miguelpeixe** [comment]
E para comentarios:

![Captura de tela de 2018-06-21 11-00-39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ceae1f82b317f7d9acf500/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2733dd5b565ed133b505e424eac5c5b5656e0ebc969f9ec6923ce4e01ffd43f5d74c63f42a9be871ebf00bb208b4d82b4bd8f1ec6e02f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee34450ac1a3066e37e377855d9.png)

**Comment by pmarkun** [comment]
Ah,

sim, esta desse jeito.

O que eu mandei é um mockup mal feito no gimp pra te dar uma ideia do que eu estava imaginando.

Essa informação linear deixa confuso.

**Comment by miguelpeixe** [comment]
Ah, entendi, vou estudar essa interface aqui

**Comment by miguelpeixe** [comment]
Resolvido
