### ISSUE TITLE
Atividade recente - Incluir botões de funil de engajamento

### ISSUE THREAD

**Issue by miguelpeixe** [lianetoolkit/liane-toolkit#32]

**Comment by pmarkun** [comment]
Quando você clica num botão ele não fica marcado. Apesar de reportar e gravar internamente a mudança de status.

**Comment by miguelpeixe** [comment]
Confirmado o bug, vou criar uma issue especifica para isso

**Comment by miguelpeixe** [comment]
Resolvido
