### ISSUE TITLE
Atividade recente - filtro por cmm/reaction

### ISSUE THREAD

**Issue by miguelpeixe** [lianetoolkit/liane-toolkit#33]

**Comment by pmarkun** [comment]
Filtro por Reactions não esta funcionando.

Na lista do Directory aparecem reactions que não aparecem no filtro.

**Comment by miguelpeixe** [comment]
Nao consigo reproduzir

**Comment by pmarkun** [comment]
Te coloquei como owner da minha campanha.

Da uma olhada lá.

Aproveita e me coloca como admin da plataforma dev pra eu poder ver se ta dando zica nos jobs.

**Comment by miguelpeixe** [comment]
Me parece que não tem reaction na sua base mesmo. Te coloquei na minha (e admin da plataforma).

**Comment by pmarkun** [comment]
ok, na sua ta rolando.

precisa ver pq é que não capturou todo o histórico da minha então.

**Comment by miguelpeixe** [comment]
Provavelmente por conta do token do aplicativo, que não retorna dados das pessoas que interagiram (apenas em caso de ser admin da página ou interação por uma outra página). Minha suposição para não retornar esses dados é que o aplicativo que usamos para testes não é público e não tem permissão manage_pages aprovada.

Ainda me é estranho pois este aplicativo que rodamos é o "clone" teste, recurso disponível pelo Facebook justamente para testar funcionalidades no que seria uma cópia do seu aplicativo em produção. Suporia que este aplicativo retornaria dados idênticos, mas não está sendo o caso.

**Comment by pmarkun** [comment]
ok, vou marcar como concluida aqui.
