### ISSUE TITLE
Maps - Context layers deverão ser checkboxes

### ISSUE THREAD

**Issue by miguelpeixe** [lianetoolkit/liane-toolkit#60]

**Comment by pmarkun** [comment]
Rolou? Aqui continua radio button.

**Comment by miguelpeixe** [comment]
Rolou, o build não tinha subido pro dev

**Comment by pmarkun** [comment]
Seria lindo se desse pra ordenar os layers. Pode ser no mapa (salvando por campanha) ou no adm.
